micronaut:
  application:
    name: mnHello
  server:
    port: ${SERVER_PORT:8090}  # ENV variable 8081 defined in app config else fallback 8090
hello:
  world:
    message: "Hello from application.yml"
    translation:
      de: "Hallo Welt"
      en: "Hello World"